name: ShareIt API Tests

on:
  pull_request:

jobs:
  build:
    uses: yandex-praktikum/java-shareit/.github/workflows/api-tests.yml@ci
    with:
      postgres-version: 15
    secrets:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test